import { Sparkles, Smartphone, Globe, Palette, Brain, ShoppingCart, Heart, Zap, Database, Shield } from "lucide-react"

export const projects = [
    {
        id: "ai-chatbot-platform",
        title: "AI-Powered Chatbot Platform",
        category: "AI Web Application",
        description: "Intelligent conversational AI with natural language processing and multi-language support",
        longDescription: "A state-of-the-art chatbot platform that leverages advanced NLP to understand and respond to user queries in real-time. It supports over 50 languages and integrates seamlessly with existing customer support systems.",
        icon: Brain,
        tags: ["AI/ML", "Next.js", "Python"],
        gradient: "from-blue-500 to-cyan-500",
        features: ["Natural Language Understanding", "Multi-language Support", "Sentiment Analysis", "Customizable Personality", "Analytics Dashboard"],
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ", // Placeholder
        screenshots: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
        testLink: "#",
    },
    {
        id: "smart-healthcare-app",
        title: "Smart Healthcare Mobile App",
        category: "AI Mobile App",
        description: "AI-driven health monitoring app with predictive analytics and telemedicine features",
        longDescription: "Revolutionizing patient care with AI. This app monitors vital signs, predicts potential health issues, and connects patients with doctors instantly. It features a secure, HIPAA-compliant architecture.",
        icon: Heart,
        tags: ["React Native", "AI", "Healthcare"],
        gradient: "from-pink-500 to-rose-500",
        features: ["Real-time Vitals Monitoring", "AI Health Predictions", "Secure Video Consultations", "Medication Reminders", "Health History Tracking"],
        videoUrl: "",
        screenshots: ["/placeholder.jpg", "/placeholder.jpg"],
        testLink: "#",
    },
    {
        id: "ecommerce-ai-recommendation",
        title: "E-Commerce AI Recommendation",
        category: "AI Web Platform",
        description: "Personalized shopping experience with AI-powered product recommendations",
        longDescription: "Boost sales and customer engagement with our AI recommendation engine. It analyzes user behavior to suggest products they are most likely to buy, increasing conversion rates by up to 30%.",
        icon: ShoppingCart,
        tags: ["AI", "E-commerce", "Analytics"],
        gradient: "from-purple-500 to-indigo-500",
        features: ["Personalized Feed", "Similar Product Suggestions", "Trend Analysis", "User Behavior Tracking", "A/B Testing Support"],
        videoUrl: "",
        screenshots: ["/placeholder.jpg", "/placeholder.jpg"],
        testLink: "#",
    },
    {
        id: "financial-dashboard",
        title: "Financial Dashboard UI/UX",
        category: "UI/UX Design",
        description: "Modern fintech dashboard with intuitive data visualization and user experience",
        longDescription: "A clean, modern, and intuitive dashboard design for a fintech platform. We focused on data visualization and ease of use, making complex financial data accessible to everyone.",
        icon: Palette,
        tags: ["Figma", "UI/UX", "Design System"],
        gradient: "from-green-500 to-emerald-500",
        features: ["Interactive Charts", "Dark/Light Mode", "Responsive Layout", "Accessible Design", "Design System Components"],
        videoUrl: "",
        screenshots: ["/placeholder.jpg", "/placeholder.jpg"],
        testLink: "#",
    },
    {
        id: "realtime-analytics",
        title: "Real-Time Analytics Platform",
        category: "Web Development",
        description: "Enterprise-grade analytics platform with real-time data processing",
        longDescription: "Process and visualize millions of data points in real-time. This platform is built for scale, using WebSocket technology to deliver live updates without page refreshes.",
        icon: Zap,
        tags: ["React", "Node.js", "WebSocket"],
        gradient: "from-yellow-500 to-orange-500",
        features: ["Live Data Streaming", "Customizable Widgets", "Role-based Access Control", "Data Export", "Alerting System"],
        videoUrl: "",
        screenshots: ["/placeholder.jpg", "/placeholder.jpg"],
        testLink: "#",
    },
    {
        id: "fitness-tracking-app",
        title: "Fitness Tracking Mobile App",
        category: "Mobile App Development",
        description: "Cross-platform fitness app with workout tracking and social features",
        longDescription: "Track your workouts, set goals, and compete with friends. This cross-platform app works seamlessly on iOS and Android, providing a unified experience for all users.",
        icon: Smartphone,
        tags: ["Flutter", "Firebase", "iOS/Android"],
        gradient: "from-teal-500 to-cyan-500",
        features: ["GPS Tracking", "Workout Plans", "Social Sharing", "Progress Analytics", "Wearable Integration"],
        videoUrl: "",
        screenshots: ["/placeholder.jpg", "/placeholder.jpg"],
        testLink: "#",
    },
    {
        id: "saas-management-portal",
        title: "SaaS Management Portal",
        category: "Web Development",
        description: "Complete SaaS solution with subscription management and admin dashboard",
        longDescription: "A comprehensive solution for managing your SaaS business. Handle subscriptions, user management, and billing all in one place with our robust admin portal.",
        icon: Globe,
        tags: ["Next.js", "Stripe", "PostgreSQL"],
        gradient: "from-violet-500 to-purple-500",
        features: ["Subscription Management", "User Roles & Permissions", "Stripe Integration", "Invoice Generation", "Activity Logs"],
        videoUrl: "",
        screenshots: ["/placeholder.jpg", "/placeholder.jpg"],
        testLink: "#",
    },
    {
        id: "blockchain-security",
        title: "Blockchain Security System",
        category: "Security & Web3",
        description: "Decentralized security platform with blockchain-based authentication",
        longDescription: "Enhance security with the power of blockchain. Our decentralized authentication system eliminates the risk of centralized data breaches and provides immutable audit trails.",
        icon: Shield,
        tags: ["Blockchain", "Security", "Web3"],
        gradient: "from-red-500 to-pink-500",
        features: ["Decentralized Identity", "Smart Contract Auditing", "Immutable Logs", "Multi-factor Authentication", "Zero-knowledge Proofs"],
        videoUrl: "",
        screenshots: ["/placeholder.jpg", "/placeholder.jpg"],
        testLink: "#",
    },
    {
        id: "restaurant-management",
        title: "Restaurant Management System",
        category: "UI/UX & Web",
        description: "Complete restaurant POS system with inventory and order management",
        longDescription: "Streamline your restaurant operations with our all-in-one management system. From table booking to kitchen display systems, we cover every aspect of restaurant management.",
        icon: Database,
        tags: ["UI/UX", "Full-Stack", "Cloud"],
        gradient: "from-amber-500 to-yellow-500",
        features: ["POS System", "Inventory Tracking", "Table Reservation", "Kitchen Display System", "Online Ordering"],
        videoUrl: "",
        screenshots: ["/placeholder.jpg", "/placeholder.jpg"],
        testLink: "#",
    },
    {
        id: "ai-content-generator",
        title: "AI Content Generator",
        category: "AI Application",
        description: "Advanced AI tool for generating marketing content and social media posts",
        longDescription: "Create engaging content in seconds. Our AI content generator helps marketers and creators produce high-quality blog posts, social media captions, and ad copy effortlessly.",
        icon: Sparkles,
        tags: ["AI", "GPT", "Content"],
        gradient: "from-indigo-500 to-blue-500",
        features: ["Blog Post Generation", "Social Media Captions", "SEO Optimization", "Tone Adjustment", "Plagiarism Checker"],
        videoUrl: "",
        screenshots: ["/placeholder.jpg", "/placeholder.jpg"],
        testLink: "",
    },
]
